### ISSUE TITLE
Adding a web UI

### ISSUE THREAD

**Issue by willbach** [taalhavras/ucal#20]
Hi @taalhavras ! I'd like to work on adding a web UI to this. I've spoken with @jalehman about it already and he said to contact you.

I'm currently looking at serving the static files on a route, and then looking at the Landscape code as a structural guide.

The next thing will be to set up something to handle pokes and subscriptions coming from/going to the UI. I'll definitely need some help with that as I haven't written anything in Hoon before.

My urbit ID is fabnev-hinmur if you want to communicate through there.

**Comment by taalhavras** [comment]
Awesome, nice to have you on board! I sent you a message on urbit, lmk if you can't see it.

I'm currently working on the code to handle scrys/pokes/subscriptions from the frontend (it's on the rather poorly named `better-scry` branch). Currently scrying is supported, pokes and subscriptions should follow soon. 

There's another person interested in doing some UI work on this - their urbit ID is ~finled-bansel. I'll let them know you're also interested and you two can figure out if you want to work together or approach from different angles.

**Comment by willbach** [comment]
I saw your invite but the DM never loaded. I'll try to start a DM and see if that works.

re: scrying: sounds good! I'll try pull that branch and check out the code.

I DM'd finled just now as well.
