### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by afknapping** [taalhavras/ucal#30]
ran into errors when trying to follow the usage guide. `yarn build` ran fine, then:

- `mount |%home` seems to be a typo
- `|mount %home` returned `dojo: generator failure`
- `|start %ucal-store` returned
  ```
  activated app home/ucal-store
  gall: failed to build agent %ucal-store
  ```
- `|start %calendar` returned
  ```
  activated app home/calendar 
  gall: failed to build agent %calendar
  ```

ship is a fakezod created with `urbit-king new --fake zod` and also running with urbit-king

**Comment by afknapping** [comment]
/v timluc

```
|mount %
|commit %home
```

then:

- `|start %ucal-store` returns `[already running %home/%ucal-store]`
- `|start %calendar` returns `[already running %home/%calendar]`

i do not see a tile in landscape though – but also not sure if that is correct expectation. is there a special url i need to go to?

**Comment by taalhavras** [comment]
thanks for catching the readme typo - that's been updated. I just ran through the install instructions with a fresh clone of the repo + a new binary from urbit.org and I see the tile. Have you tried hard refreshing the page? You can also try going to
`http://localhost:PORT/~calendar` where PORT is whatever you happen to be running on.

**Comment by antsankov** [comment]
Ping again on this thread, installed and ran:
```
> |start %ucal-store
>=
[already running %home/%ucal-store]
```
and 
```
> |start %calendar
>=
[already running %home/%calendar]
```

Am I missing something here? Don't see it in landscape and restarted my ship. 
<img width="1359" alt="Screen Shot 2021-04-15 at 22 25 46" src="https://user-images.githubusercontent.com/2533512/114962908-9b413b00-9e39-11eb-981a-3b55fe05b443.png">

Do not see the tile in landscape, even after hard restart.

**Comment by taalhavras** [comment]
Can you try
`|fade %ucal-store`
`|fade %ucal-pull-hook`
`|fade %ucal-push-hook`
`|fade %calendar`
to stop the apps and then restart them (run `|start %app-name` again)? You don't need to run the pull/push hook fades if you never started them.

**Comment by antsankov** [comment]
When I run the first command, %ucal-store I get. I am using a star to play with it, would the ship type affect this? 
 
```
crud: %belt event failed
[%poke %belt]
  bar-stack
~[
  ~[/gall/use/hood/0w3.BHu53/~rabrel/drum/fade/ucal-store /dill //term/1]
  ~[/gall/use/dojo/0w3.BHu53/out/~rabrel/hood/drum_~rabrel/poke /dill //term/1]
  ~[/dill //term/1]
  ~[
    /gall/use/dojo/0w3.BHu53/~rabrel/drum_~rabrel/hand/gen/hood/fade
    /dill
    //term/1
  ]
  ~[
    /gall/use/hood/0w3.BHu53/out/~rabrel/dojo/drum/phat/~rabrel/dojo
    /dill
    //term/1
  ]
  ~[/dill //term/1]
  ~[//term/1]
]
call: failed
/sys/vane/gall/hoon:<[1.673 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.674 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.677 3].[1.710 5]>
[ %gall-call-failed
  ~[/gall/use/hood/0w3.BHu53/~rabrel/drum/fade/ucal-store /dill //term/1]
  [%fade dap=%ucal-store style=%slay]
]
/sys/vane/gall/hoon:<[1.678 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.680 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.681 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.707 14].[1.707 59]>
/sys/vane/gall/hoon:<[1.707 22].[1.707 59]>
/sys/vane/gall/hoon:<[794 5].[805 12]>
/sys/vane/gall/hoon:<[795 5].[805 12]>
/sys/vane/gall/hoon:<[796 5].[805 12]>
/sys/vane/gall/hoon:<[796 14].[796 37]>
/sys/vane/gall/hoon:<[983 7].[984 55]>
/sys/vane/gall/hoon:<[984 7].[984 55]>
/sys/vane/gall/hoon:<[984 27].[984 54]>
```

**Comment by taalhavras** [comment]
is your star up to date with the latest OTA? and can you `|fade %calendar`? or does that also error out?

**Comment by antsankov** [comment]
Yes it is updated: 

When I run |fade %calendar I get:
```
>=
[fade not running %home/%ucal-push-hook]
crud: %belt event failed
[%poke %belt]
  bar-stack
~[
  ~[/gall/use/hood/0w3.BHu53/~rabrel/drum/fade/calendar /dill //term/1]
  ~[/gall/use/dojo/0w3.BHu53/out/~rabrel/hood/drum_~rabrel/poke /dill //term/1]
  ~[/dill //term/1]
  ~[
    /gall/use/dojo/0w3.BHu53/~rabrel/drum_~rabrel/hand/gen/hood/fade
    /dill
    //term/1
  ]
  ~[
    /gall/use/hood/0w3.BHu53/out/~rabrel/dojo/drum/phat/~rabrel/dojo
    /dill
    //term/1
  ]
  ~[/dill //term/1]
  ~[//term/1]
]
call: failed
/sys/vane/gall/hoon:<[1.673 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.674 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.677 3].[1.710 5]>
[ %gall-call-failed
  ~[/gall/use/hood/0w3.BHu53/~rabrel/drum/fade/calendar /dill //term/1]
  [%fade dap=%calendar style=%slay]
]
/sys/vane/gall/hoon:<[1.678 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.680 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.681 3].[1.710 5]>
/sys/vane/gall/hoon:<[1.707 14].[1.707 59]>
/sys/vane/gall/hoon:<[1.707 22].[1.707 59]>
/sys/vane/gall/hoon:<[794 5].[805 12]>
/sys/vane/gall/hoon:<[795 5].[805 12]>
/sys/vane/gall/hoon:<[796 5].[805 12]>
/sys/vane/gall/hoon:<[796 14].[796 37]>
/sys/vane/gall/hoon:<[983 7].[984 55]>
/sys/vane/gall/hoon:<[984 7].[984 55]>
/sys/vane/gall/hoon:<[984 27].[984 54]>
```

Not sure what to make of any of it I'm afraid, but it is interesting.

**Comment by philipcmonk** [comment]
That error looks to me like it's saying the app has already been faded from gall's perspective, but hood/drum doesn't think so, so it won't let you fade it again.  Does ucal start or stop apps on its own?

You should be able to restart it with `|pass [%g %conf %calendar]`, and the same for the other apps.  You can fade them again after that with `|fade`.

**Comment by taalhavras** [comment]
ucal definitely doesn't start/stop things on its own so I'm not sure how that could have happened.

**Comment by patosullivan** [comment]
FWIW I ran into these exact same issues and unfortunately @philipcmonk's advice didn't seem to resolve it.
